version: "0.0.1"
services:
  code_fragment_server:
    image: code_fragment_server:latest
    container_name: code_fragment_server
    restart: always
    volumes:
    # 挂载容器卷事件与宿主机事件同步
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /leaper/code_fragment/code_fragment_server/data/logs:/app/logs
    ports:
      - "8888:8888"
    networks:
      - leaper
    environment:
      - CF_HOST=cf_mysql
      - CF_PORT=3306
      - CF_USERNAME=root
      - CF_PASSWORD=root
      - CF_DATABASE=code_fragment
      - NODE_ENV=production
  cf_mysql:
    image: mysql:5.7
    container_name: cf_mysql
    restart: always
    command: --port 3306 --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - /leaper/code_fragment/code_fragment_server/data/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=code_fragment
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - leaper
networks:
  leaper:
    external: true
